export const campaignListContants = {
    GET_CAMPAIGN_LIST_REQUEST: 'GET_CAMPAIGN_LIST_REQUEST',
    GET_CAMPAIGN_LIST_SUCCESS: 'GET_CAMPAIGN_LIST_SUCCESS',
    GET_CAMPAIGN_LIST_FAILURE: 'GET_CAMPAIGN_LIST_FAILURE',

    FILTER_CAMPAIGN_BY_DATE: 'FILTER_CAMPAIGN_BY_DATE',
    FILTER_CAMPAIGN_BY_NAME: 'FILTER_CAMPAIGN_BY_NAME'
};