export const campaignListContants = {
    GET_CAMPAIGN_LIST_REQUEST: 'GET_CAMPAIGN_LIST_REQUEST',
    GET_CAMPAIGN_LIST_SUCCESS: 'GET_CAMPAIGN_LIST_SUCCESS',
    GET_CAMPAIGN_LIST_FAILURE: 'GET_CAMPAIGN_LIST_FAILURE',

    GET_FILTERED_CAMPAIGN: 'GET_FILTERED_CAMPAIGN'
};